export const ADD_TASK = 'ADD_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const MOVE_TASK = 'MOVE_TASK'
export const SORT_TASK = 'SORT_TASK'
export const TOGGLE_STATUS = 'TOGGLE_STATUS'